apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-web-deployment
  labels:
    node: service
spec:
  replicas: 1
  selector:
    matchLabels:
      node: service
  template:
    metadata:
      labels:
        node: service
    spec:
      containers:
      - name: shopping-web-container
        image: asia.gcr.io/eunoia0523/shopping:v1
        ports:
        - containerPort: 8080
        resources:
          requests: ## 오토파일럿 모드에서 없으면 에러 발생 
            memory: "100Mi"
            cpu: "250m"
          limits: ## limit이 없으면 오토스케일링 문제 발생  
            cpu: "500m"
